language: minimal

os:
  - linux
  - osx
  - windows

env:
  - DENO_VERSION=v0.10.0

before_script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then iex (new-object net.webclient).downloadstring('https://get.scoop.sh'); fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then scoop install deno; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then curl -sL https://deno.land/x/install/install.sh | sh -s $DENO_VERSION; fi
  - $HOME/.deno/bin/deno version
  - $HOME/.deno/bin/deno fetch https://deno.land/std@v0.9.0/http/file_server.ts

script:
  - $HOME/.deno/bin/deno -A ./test.ts
