
on : [ push , pull_request ]

name : test

jobs:
    test:
        name : Deno ${{ matrix.deno }} test in ${{ matrix.os }}
        runs-on : ${{ matrix.os }}
        
        strategy:
            matrix:
                deno : ['v1.x']
                os : [ ubuntu-latest , macOS-latest , windows-latest ]
        
        steps:
            
            -   uses : actions/checkout@v2
            
            -
                name : Setup deno
                uses : denolib/setup-deno@v2
                with:
                    deno-version : ${{ matrix.deno }}

            - 
                name : Env
                run: |
                    deno --version

            - 
                name : Check code format
                run : deno fmt --check
                if : runner.os != 'Windows'
                env:
                    RUST_BACKTRACE : 1
            
            -   name : Test
                run : deno test -A
                env:
                    RUST_BACKTRACE: 1
